### ISSUE TITLE
ValueError: base_conditional() arguments 

### ISSUE THREAD

**Issue by yangmenglinsite** [FelixOpolka/GGP-TF2#1]
ValueError: base_conditional() arguments [Note that this check verifies the shape of an alternative representation of Kmn. See the docs for the actual expected shape.].  Specified by tensor shape=(140, 140) dtype=float64 dimension -1.  Tensor shape=(1,) dtype=float64 dimension -1 must have size 140.  Received size 1, shape (1,)

**Comment by FelixOpolka** [comment]
You seem to have been using a too recent version of GPflow. I have pushed some changes to the repository and updated the code to use GPflow 2 now.
